# Generated by Django 3.2.9 on 2022-06-25 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='transcation',
            name='balance_in_bank',
            field=models.FloatField(),
        ),
    ]
