# Generated by Django 3.2.9 on 2022-06-25 16:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20220625_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcation',
            name='amount_spend',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='transcation',
            name='transaction_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 25, 22, 3, 39, 500090)),
        ),
    ]
